/*
 * generated by Xtext
 */
package ru.nsu.fit.protlang.pl4j.ui.contentassist

import ru.nsu.fit.protlang.pl4j.ui.contentassist.AbstractPl4jProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class Pl4jProposalProvider extends AbstractPl4jProposalProvider {
}
