/*
 * generated by Xtext
 */
package ru.nsu.fit.protlang.pl4j;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Pl4jRuntimeModule extends ru.nsu.fit.protlang.pl4j.AbstractPl4jRuntimeModule {

}
