/*
 * generated by Xtext
 */
package ru.nsu.fit.protlang.pl4j;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class Pl4jStandaloneSetup extends Pl4jStandaloneSetupGenerated{

	public static void doSetup() {
		new Pl4jStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

