/*
 * generated by Xtext
 */
package ru.nsu.fit.protlang.pl4j.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class Pl4jUiModule extends ru.nsu.fit.protlang.pl4j.ui.AbstractPl4jUiModule {
	public Pl4jUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
